### ISSUE TITLE
.gitigore update, node?

### ISSUE THREAD

**Issue by louire** [AriDevK/Rocket-PS#1]
A web framework without ignoring node modules?

![Auuuuu Dog](https://64.media.tumblr.com/fb37f2b00b5630c08bffffead03cacb7/23bb5736ff0b0b5f-3c/s640x960/400bde13863ec26d16c6e59b1671c3841111b163.gif)

**Comment by AriDevK** [comment]
wdym? are we gonna use node on this project?
Give me examples please

**Comment by louire** [comment]
<3

**Comment by louire** [comment]
For example, you could use Node.js to build a front-end for your PowerShell web application using a framework like React or Angular. This would allow you to create a more interactive and responsive user interface for your web application.

Additionally, Node.js has a rich ecosystem of modules and libraries that can be used to add functionality to your web application, such as authentication, authorization, and database integration. These modules can be easily installed and managed using Node.js's package manager, npm.

**Comment by AriDevK** [comment]
This repository is made to save the source code of the framework; it will not have any complex case of use like adding React, Angular, etc.

But in a future would be an innovative idea to add a documentation page and deploy it at once with the new framework versions.
let's going to do it

![Baby, I'm preying on you tonight
Hunt you down, eat you alive
Just like animals, animals
Like animals-mals](https://github.com/AriDevK/Rocket-PS/assets/42656298/00779d05-e236-48eb-ab0d-b27ce875e0e2)
